import Head from "next/head";

import { Inter } from "@next/font/google";
import HomeSearch from "../components/Home/HomeSearch";
import HomeOffers from "../components/Home/HomeOffers";
import HomeProducts from "../components/Home/HomeProducts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Commerce Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeSearch />
        <HomeOffers />
        <HomeProducts />
      </main>
    </>
  );
}
